"""modelo inicial

Revision ID: adddc119b764
Revises: 
Create Date: 2026-05-28 16:26:18.917943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adddc119b764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('zona_horaria', sa.String(length=64), nullable=False),
    sa.Column('email_notificaciones', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('redes', sa.String(length=1000), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negocios_slug'), 'negocios', ['slug'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_negocio_id'), 'categorias', ['negocio_id'], unique=False)
    op.create_table('portafolio_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portafolio_imagenes_negocio_id'), 'portafolio_imagenes', ['negocio_id'], unique=False)
    op.create_table('profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('calificacion_promedio', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesionales_negocio_id'), 'profesionales', ['negocio_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('rol', sa.Enum('cliente', 'admin', 'super_admin', name='rolusuario'), nullable=False),
    sa.Column('google_id', sa.String(length=120), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('turnos_completados', sa.Integer(), nullable=False),
    sa.Column('turnos_cancelados', sa.Integer(), nullable=False),
    sa.Column('no_shows', sa.Integer(), nullable=False),
    sa.Column('primera_visita', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_visita', sa.DateTime(timezone=True), nullable=True),
    sa.Column('segmento', sa.Enum('nuevo', 'regular', 'fiel', 'en_riesgo', name='segmentocliente'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'email', name='uq_cliente_negocio_email')
    )
    op.create_index(op.f('ix_clientes_negocio_id'), 'clientes', ['negocio_id'], unique=False)
    op.create_table('excepciones_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('no_disponible', 'horario_especial', name='tipoexcepcion'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excepciones_agenda_profesional_id'), 'excepciones_agenda', ['profesional_id'], unique=False)
    op.create_table('horarios_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_recurrentes_profesional_id'), 'horarios_recurrentes', ['profesional_id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('buffer_min', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.Column('badge', sa.Enum('ninguno', 'recomendado', 'popular', 'nuevo', name='badgeservicio'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_negocio_id'), 'servicios', ['negocio_id'], unique=False)
    op.create_table('profesional_servicio',
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('profesional_id', 'servicio_id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('confirmada', 'cancelada', 'completada', 'no_show', name='estadoreserva'), nullable=False),
    sa.Column('total_precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_duracion', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frecuencia_recordatorio_dias', sa.Integer(), nullable=True),
    sa.Column('token_cancelacion', sa.String(length=64), nullable=False),
    sa.Column('notas', sa.String(length=2000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profesional_id', 'inicio', name='uq_reserva_profesional_inicio')
    )
    op.create_index(op.f('ix_reservas_cliente_id'), 'reservas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_reservas_negocio_id'), 'reservas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_reservas_profesional_id'), 'reservas', ['profesional_id'], unique=False)
    op.create_index(op.f('ix_reservas_token_cancelacion'), 'reservas', ['token_cancelacion'], unique=True)
    op.create_table('notificacion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('confirmacion_cliente', 'aviso_admin', 'recordatorio_frecuencia', 'sugerencia_inasistencia', name='tiponotificacion'), nullable=False),
    sa.Column('destinatario', sa.String(length=255), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'fallido', name='estadonotificacion'), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordatorios_programados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('frecuencia', 'inasistencia', name='tiporecordatorio'), nullable=False),
    sa.Column('enviar_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'cancelado', name='estadorecordatorio'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordatorios_programados_enviar_en'), 'recordatorios_programados', ['enviar_en'], unique=False)
    op.create_index(op.f('ix_recordatorios_programados_reserva_id'), 'recordatorios_programados', ['reserva_id'], unique=False)
    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('profesional_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=2000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['profesional_id'], ['profesionales.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resenas_negocio_id'), 'resenas', ['negocio_id'], unique=False)
    op.create_table('reserva_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_items_reserva_id'), 'reserva_items', ['reserva_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reserva_items_reserva_id'), table_name='reserva_items')
    op.drop_table('reserva_items')
    op.drop_index(op.f('ix_resenas_negocio_id'), table_name='resenas')
    op.drop_table('resenas')
    op.drop_index(op.f('ix_recordatorios_programados_reserva_id'), table_name='recordatorios_programados')
    op.drop_index(op.f('ix_recordatorios_programados_enviar_en'), table_name='recordatorios_programados')
    op.drop_table('recordatorios_programados')
    op.drop_table('notificacion_logs')
    op.drop_index(op.f('ix_reservas_token_cancelacion'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_profesional_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_negocio_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_cliente_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_table('profesional_servicio')
    op.drop_index(op.f('ix_servicios_negocio_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_horarios_recurrentes_profesional_id'), table_name='horarios_recurrentes')
    op.drop_table('horarios_recurrentes')
    op.drop_index(op.f('ix_excepciones_agenda_profesional_id'), table_name='excepciones_agenda')
    op.drop_table('excepciones_agenda')
    op.drop_index(op.f('ix_clientes_negocio_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_profesionales_negocio_id'), table_name='profesionales')
    op.drop_table('profesionales')
    op.drop_index(op.f('ix_portafolio_imagenes_negocio_id'), table_name='portafolio_imagenes')
    op.drop_table('portafolio_imagenes')
    op.drop_index(op.f('ix_categorias_negocio_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_negocios_slug'), table_name='negocios')
    op.drop_table('negocios')
    # ### end Alembic commands ###
