"""resena_publica

Revision ID: 0bad9fc05dd3
Revises: 6ef05f0bd726
Create Date: 2026-05-28 21:57:52.079998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bad9fc05dd3'
down_revision: Union[str, None] = '6ef05f0bd726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resenas', sa.Column('autor_nombre', sa.String(length=120), nullable=True))
    op.add_column('resenas', sa.Column('autor_email', sa.String(length=255), nullable=True))
    op.alter_column('resenas', 'reserva_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('resenas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resenas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resenas', 'reserva_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resenas', 'autor_email')
    op.drop_column('resenas', 'autor_nombre')
    # ### end Alembic commands ###
