"""auth admin y registro de accesos

Revision ID: 6ef05f0bd726
Revises: adddc119b764
Create Date: 2026-05-28 18:03:39.758664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef05f0bd726'
down_revision: Union[str, None] = 'adddc119b764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=True),
    sa.Column('ingreso_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_acceso_negocio_id'), 'registros_acceso', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_registros_acceso_usuario_id'), 'registros_acceso', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('username', sa.String(length=60), nullable=True))
    op.add_column('usuarios', sa.Column('dni', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('ultimo_login_en', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'ultimo_login_en')
    op.drop_column('usuarios', 'activo')
    op.drop_column('usuarios', 'password_hash')
    op.drop_column('usuarios', 'dni')
    op.drop_column('usuarios', 'username')
    op.drop_index(op.f('ix_registros_acceso_usuario_id'), table_name='registros_acceso')
    op.drop_index(op.f('ix_registros_acceso_negocio_id'), table_name='registros_acceso')
    op.drop_table('registros_acceso')
    # ### end Alembic commands ###
